Repository GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp, pull requests merged in 2020-10, with the labels that each got.

#64 Grant prow service account presubmit IAM permissions
  test/infra/anthos-managed/namespaces/secretmanager-csi-build/iam-policy.yaml
Labels: lgtm, size/XS

#66 Grant prow SA viewer permissions on project
  test/infra/anthos-managed/namespaces/secretmanager-csi-build/iam-policy.yaml
Labels: lgtm, size/XS

#67 add an owners file
  OWNERS
Labels: lgtm, size/XS

#65 📖: clarify that support should be done through github issues
  README.md
Labels: lgtm, size/XS

#63 Add instructions on exporting kubeconfig file for Prow
  test/e2e/Dockerfile
  test/e2e/mount_test.go
  test/infra/README.md
  test/infra/prow/presubmit.sh
Labels: approved, lgtm, size/M

#70 tests: build & deploy the plugin from the git commit
  deploy/provider-gcp-plugin.yaml.tmpl
  scripts/deploy.sh
  test/e2e/Dockerfile
  test/e2e/mount_test.go
  test/infra/prow/Dockerfile
  test/infra/prow/presubmit.sh
Labels: approved, lgtm, size/S

#69 main: cleanup socket before attempting to listen
  CHANGELOG.md
  main.go
Labels: approved, size/S

#71 gosec: add gosec check github runner
  .github/workflows/test.yml
  Makefile
  test/e2e/test-secret-mounter/test-secret-mounter.go
  tools/go.mod
  tools/go.sum
  tools/tools.go
Labels: approved, lgtm, size/M

#73 Add a hyperlink in README for example
  README.md
Labels: approved, lgtm, size/XS
