Repository GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp, pull requests merged in 2021-09, with the labels that each got.

#138 tests: add a load test
  docs/testing-notes.md
  scripts/load-test.sh
  test/e2e/templates/load-many-secrets.yaml.tmpl
  test/e2e/templates/load-one-secret.yaml.tmpl
Labels: lgtm, approved, size/L

#139 test: rotation
  test/e2e/Dockerfile
  test/e2e/enable-rotation.sh
  test/e2e/mount_test.go
  test/e2e/templates/test-rotate.yaml.tmpl
Labels: lgtm, approved, size/L

#140 test: e2e test for secret syncing to k8s secrets
  test/e2e/mount_test.go
  test/e2e/templates/test-sync.yaml.tmpl
Labels: lgtm, approved, size/L

#137 chore: build and test against go 1.17
  .github/workflows/test.yml
  Dockerfile
  Makefile
  go.mod
  go.sum
  test/e2e/Dockerfile
  tools/go.mod
  tools/go.sum
  tools/tools.go
Labels: lgtm, approved, size/L

#141 docs: add link to testgrid for periodic tests
  README.md
Labels: size/XS, lgtm, approved

#142 Update provider-gcp-plugin.yaml
  deploy/provider-gcp-plugin.yaml
Labels: lgtm, size/M, ok-to-test

#144 v0.6.0: update deploy + changelog
  CHANGELOG.md
  deploy/provider-gcp-plugin.yaml
  docs/releasing.md
Labels: size/S, lgtm, approved

#145 v0.6.0: update deploy + changelog (#144)
  CHANGELOG.md
  deploy/provider-gcp-plugin.yaml
  docs/releasing.md
Labels: size/S, lgtm, approved
